name: asr-segmentation
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - tifffile
  - imagecodecs
  - scipy
  - pytorch
